---
cluster: # Group name
  hosts: # Hosts inside group
    eddy1:
      ansible_host: 10.4.248.56
    eddy2:
      ansible_host: 10.4.248.195
    eddy3:
      ansible_host: 10.4.248.76
    katy1:
      ansible_host: 10.4.248.214
    louie1:
      ansible_host: 10.4.248.87

elasticsearch:
  hosts:
    eddy1:
      rack: b1
    eddy2:
      rack: b2
    eddy3:
      rack: b1
    katy1:

master_nodes:
  hosts:
    eddy1:
    eddy2:
    eddy3:

data_nodes:
  hosts:
    eddy1:
    eddy2:
    eddy3:

coord_only_nodes:
  hosts:
    katy1:

kibana:
  hosts:
    katy1:

logstash:
  hosts:
    louie1:

all:
  children: # Groups
    cluster:
