---
cluster: # Group name
  hosts: # Hosts inside group
    node-1:
      ansible_host: 10.0.1.11 # ansible_host only works for static ips
    node-2:
      ansible_host: 10.0.1.12 # ansible_host only works for static ips
    node-3:
      ansible_host: 10.0.1.13 # ansible_host only works for static ips
    # node-4:
    #   ansible_host: 10.0.1.20
    # node-5:
    #   ansible_host: 10.0.1.30

elasticsearch:
  hosts:
    node-1:
    node-2:
    node-3:

# kibana:
#   hosts:
#     node-4:

all:
  children: # Groups
    cluster:
