# Steps followed from https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
---
- name: Download and add Elastic GPG public signing key
  become: yes
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Save the Elasticsearch repository definition
  become: yes
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: '{{ elastic_repo_url }}'
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: no
    state: present

- name: Install Elasticsearch
  become: yes
  package:
    name: 'elasticsearch-{{ elastic_version }}'
    state: present
