---
- name: Download and Install Logstash and Requirements
  hosts: logstash
  gather_facts: no
  pre_tasks:
    - name: Establish SSH connection
      import_role:
        name: establish-connection
  tasks:
    - name: Update hosts
      import_role:
        name: update-hosts

    - name: Install Logstash
      import_role:
        name: logstash
        tasks_from: install.yml

    - name: Adjust Firewall
      import_role:
        name: logstash
        tasks_from: firewall.yml

    - name: Configure Logstash
      import_role:
        name: logstash
        tasks_from: configure.yml
