---
# Authentication variables
default_ssh_user: elastic-user            # user when ssh into hosts
ssh_key_filename: elastic-key.pem         # filename of ssh key file
ssh_key_path: /home/elastic-user/.ssh     # path to ssh key file

# Ansible variables
ansible_ssh_user: '{{ default_ssh_user }}'
ansible_ssh_private_key_file: '{{ ssh_key_path }}/{{ ssh_key_filename }}'
ansible_python_interpreter: /usr/bin/python3 # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine
